language: php
php:
  - 5.4
env:
  - SYMFONY="2.6.*"
before_script:
  - composer update --prefer-dist
script:
#  - bin/phpunit
  - bin/phpcs -p --standard=$TRAVIS_BUILD_DIR/vendor/ongr/ongr-strict-standard/ONGR --ignore=vendor/,Tests/app/,Resources/public/ ./src
