base_user:
    resource: "@BaseUserBundle/Controller/"
    type:     annotation
    prefix:   /

base_main:
    resource: "@BaseMainBundle/Controller/"
    type:     annotation
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

BCCCronManagerBundle:
    resource: "@BCCCronManagerBundle/Resources/config/routing.xml"
    prefix:   /cron

base_user_fos:
    resource: "@BaseUserBundle/Resources/config/routing.yml"
    prefix: /

base_static:
    resource: "@BaseStaticBundle/Controller/"
    type:     annotation
    prefix:   /

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"