security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /login.html
                use_referer: true
            logout:
                path:   /logout.html
                target: /

            anonymous: ~

        login:
            pattern: ^/login.html$
            security: false

            remember_me:
                key: "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER

    access_control:
        #cron bundle
        - { path: ^/cron, role: ROLE_ADMIN }

        #admin only, but public
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }

        #general
        - { path: ^/js/routing, role: IS_AUTHENTICATED_ANONYMOUSLY }

        #user bundle
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout.html, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reset-password, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/profile, role: ROLE_USER }

        - { path: ^/users, role: ROLE_ADMIN }

        #static bundle
        - { path: ^/pages, role: ROLE_ADMIN }
        - { path: ^/page, role: IS_AUTHENTICATED_ANONYMOUSLY }